apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sealed-secrets.yaml
  - cert-manager.yaml
  - external-dns.yaml
  - longhorn.yaml
  - kyverno.yaml
  - weave-gitops.yaml
  - weave-gitops-secret.yaml
