apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ./cilium-bgp-auth-secret.yaml
patches:
  - target:
      kind: CiliumBGPClusterConfig
      name: cilium-bgp
    patch: |
      - op: replace
        path: /spec/bgpInstances/0/localASN
        value: 64513
      - op: replace
        path: /spec/bgpInstances/0/peers/0/peerASN
        value: 64512
